pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/naveen200612/student_management_system.git'
            }
        }
        stage ('Parallel Checks') {
            parallel {
                stage ('Frontend Check') {
                    steps {
                        dir('project_3') {
                            bat 'python frontend_check.py'
                        }
                    }
                }
                stage ('Backend Check') {
                    steps {
                        dir('project_3') {
                            bat 'python backend_check.py'
                        }
                    }
                }
            }
        }
        stage('Summary') {
            steps {
                echo 'Both frontend and backend checks are complete.'
            }
        }
    }
}
