pipeline {
    agent any
    parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev', 'staging', 'prod'], description: 'Select the deployment environment')
    }
    stages {
        stage ('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com'
            }
        }
        stage('Show Parameter') {
            steps {
                echo "Selected environment in Jenkins: ${params.ENVIRONMENT}"
            }
        }
        stage ('Run Python Application') {
            steps {
                // Runs the python script and passes the selected parameter as an argument
                bat "python app.py ${params.ENVIRONMENT}"
            }
        }
    }
}
