pipeline {
    agent any
    stages {
        stage ('Checkout') {
            steps {
                // Pulls code from your GitHub repo
                git branch: 'main', url: 'https://github.com'
            }
        }
        stage ('Generate Report') {
            steps {
                // Runs the Python script to produce the text file
                bat 'python app.py'
            }
        }
        stage ('Archive Student Report') {
            steps {
                // Archives the text file so it can be downloaded from the Jenkins UI
                archiveArtifacts artifacts: 'student_report.txt', fingerprint: true
            }
        }
    }
}
