pipeline {
    agent any
    stages {
        stage ('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/naveen200612/student_management_system.git'
            }
        }
        stage ('Generate Report') {
            steps {
                // Navigate into the project folder before running python
                dir('project_2') {
                    bat 'python app.py'
                }
            }
        }
        stage ('Archive Report') {
            steps {
                // Archive the report from inside the folder
                archiveArtifacts artifacts: 'project_2/report.txt', fingerprint: true
            }
        }
    }
}
